### ISSUE TITLE
Fix help/info screen when running program without any parameters.

### ISSUE THREAD

**Issue by martivo** [entigolabs/entigo-k8s-gitops#8]
Would be nice to show a help/info screen instead.
```
root@aec009413a26:/go/gitops# ./bin/gitops 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/entigolabs/entigo-k8s-gitops/internal/operations.chooseOperation(0x0)
        /go/gitops/internal/operations/operations.go:18 +0x245
github.com/entigolabs/entigo-k8s-gitops/internal/operations.Operate()
        /go/gitops/internal/operations/operations.go:13 +0x25
main.main()
        /go/gitops/cmd/gitops/main.go:13 +0x25
```

Same story with
```
root@aec009413a26:/go/gitops# ./bin/gitops --help
[error] Unsupported operation: --help
root@aec009413a26:/go/gitops# ./bin/gitops help
[error] Unsupported operation: help

```
Or with update and no parameters

```
root@aec009413a26:/go/gitops# ./bin/gitops update
using tokenized path
changed directory to: /go/gitops/gitops-workdir
panic: runtime error: slice bounds out of range [:-4]

goroutine 1 [running]:
github.com/entigolabs/entigo-k8s-gitops/internal/operations/update.getRepositoryName(0x7c84d9, 0xc0000b49e0)
        /go/gitops/internal/operations/update/repository.go:185 +0xaa
github.com/entigolabs/entigo-k8s-gitops/internal/operations/update.doesRepoExist(0x8a9300)
        /go/gitops/internal/operations/update/repository.go:103 +0x26
github.com/entigolabs/entigo-k8s-gitops/internal/operations/update.cloneIfNecessary()
        /go/gitops/internal/operations/update/update.go:25 +0x2a
github.com/entigolabs/entigo-k8s-gitops/internal/operations/update.Update.func1()
        /go/gitops/internal/operations/update/update.go:15 +0x2a
github.com/entigolabs/entigo-k8s-gitops/internal/operations.executeOperation(...)
        /go/gitops/internal/operations/operations.go:33
github.com/entigolabs/entigo-k8s-gitops/internal/operations.Operate()
        /go/gitops/internal/operations/operations.go:14 +0x2e
main.main()
        /go/gitops/cmd/gitops/main.go:13 +0x25

```

**Comment by kertkukk** [comment]
During circular dependency fix help screen was implemented. @martivo
